app:
  env: development
  debug: true
server:
  host: 0.0.0.0
  port: ${APP_PORT}
  public_host: https://${NGROK_DOMAIN}
telegram:
  token: ${TELEGRAM_TOKEN}
  admin_ids:
    - ${TELEGRAM_USER_ID}
  webhook_secret_token: DEFINITELY_NOT_A_SECRET
