name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: ./.github/actions/setup_environment
        with:
          python-enabled: true
          poetry-enabled: true
          zizmor-enabled: true

      - name: Install Dependencies
        run: |
          task init

      - name: Lint PR
        run: |
          task lint
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for Zizmor

      - name: Prepare auxiliary containers
        working-directory: docker
        run: |
          task build
          task start
        env:
          ENVIRONMENT: CI

      - name: Test backend in container
        working-directory: backend
        run: |
          task test-container

      - name: Clean up auxiliary containers
        if: success() || failure()
        working-directory: docker
        run: |
          task clean
        env:
          ENVIRONMENT: CI
